- name: Download Nexus tarball
  get_url:
    url: "{{ nexus_download_url }}"
    dest: /tmp/nexus.tar.gz
    mode: '0644'

- name: Extract Nexus archive
  unarchive:
    src: /tmp/nexus.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move Nexus directory to install path
  command: mv /tmp/nexus-{{ nexus_version }} {{ nexus_install_dir }}
  args:
    removes: /tmp/nexus-{{ nexus_version }}

- name: Move sonatype-work directory to data path
  command: mv /tmp/sonatype-work {{ nexus_data_dir }}
  args:
    removes: /tmp/sonatype-work
