- name: Download Nexus tarball
  get_url:
    url: "{{ nexus_download_url }}"
    dest: /tmp/nexus.tar.gz
    mode: '0644'

- name: Extract Nexus archive
  unarchive:
    src: /tmp/nexus.tar.gz
    dest: "{{ nexus_install_dir }}"
    remote_src: yes

- name: Set Nexus extracted directory
  set_fact:
    nexus_extracted_path: "{{ nexus_install_dir }}/nexus-{{ nexus_version }}"

- name: Make nexus startup script executable
  file:
    path: "{{ nexus_extracted_path }}/bin/nexus"
    mode: '0755'

- name: Start Nexus server
  command: "{{ nexus_extracted_path }}/bin/nexus start"
  args:
    chdir: "{{ nexus_extracted_path }}"
  async: 30
  poll: 0