- name: Download Nexus tarball
  get_url:
    url: "{{ nexus_download_url }}"
    dest: /tmp/nexus.tar.gz
    mode: '0644'

- name: Extract Nexus archive
  unarchive:
    src: /tmp/nexus.tar.gz
    dest: "{{ nexus_install_dir }}"
    remote_src: yes

- name: Set Nexus extracted directory
  set_fact:
    nexus_extracted_path: "{{ nexus_install_dir }}/nexus-{{ nexus_version }}"

- name: Make nexus startup script executable
  file:
    path: "{{ nexus_extracted_path }}/bin/nexus"
    mode: '0755'

- name: Create systemd service file for Nexus
  copy:
    dest: /etc/systemd/system/nexus.service
    content: |
      [Unit]
      Description=Nexus Repository Manager
      After=network.target

      [Service]
      Type=forking
      ExecStart={{ nexus_extracted_path }}/bin/nexus start
      ExecStop={{ nexus_extracted_path }}/bin/nexus stop
      User={{ nexus_user }}
      Restart=on-abort
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target
  mode: '0644'

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Nexus service
  systemd:
    name: nexus
    enabled: yes
    state: started
