---
- name: Define Maven version
  set_fact:
    maven_version: "3.9.4"
    maven_url: "https://dlcdn.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    maven_install_dir: "/opt/maven"

- name: Install required dependencies
  apt:
    name: tar
    state: present
    update_cache: yes

- name: Download Maven archive
  get_url:
    url: "{{ maven_url }}"
    dest: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"
    mode: '0644'

- name: Extract Maven archive
  unarchive:
    src: "/tmp/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: /opt/
    remote_src: yes
    creates: "{{ maven_install_dir }}"

- name: Rename extracted folder to maven
  command: mv /opt/apache-maven-{{ maven_version }} "{{ maven_install_dir }}"
  args:
    removes: "{{ maven_install_dir }}"
  register: mv_maven
  changed_when: mv_maven.rc == 0

- name: Set environment variables for Maven
  copy:
    dest: /etc/profile.d/maven.sh
    content: |
      export M2_HOME={{ maven_install_dir }}
      export PATH=${M2_HOME}/bin:${PATH}
    mode: '0755'

- name: Load Maven environment variables
  shell: source /etc/profile.d/maven.sh
  args:
    executable: /bin/bash
