---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Maven package
  apt:
    name: maven
    state: present

- name: Ensure Maven is installed and check version
  command: mvn -version
  register: maven_version_output
  changed_when: false

- name: Show installed Maven version
  debug:
    msg: "{{ maven_version_output.stdout }}"

