- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'
  tags: helm

- name: Run Helm install script
  command: /tmp/get_helm.sh
  tags: helm
