- name: Download Trivy binary
  get_url:
    url: "https://github.com/aquasecurity/trivy/releases/download/v{{ trivy_version }}/trivy_{{ trivy_version }}_Linux-64bit.tar.gz"
    dest: /tmp/trivy.tar.gz
    mode: '0644'

- name: Create directory for Trivy
  file:
    path: /opt/trivy
    state: directory
    mode: '0755'

- name: Extract Trivy
  unarchive:
    src: /tmp/trivy.tar.gz
    dest: /opt/trivy/
    remote_src: yes

- name: Link Trivy binary globally
  file:
    src: /opt/trivy/trivy
    dest: /usr/local/bin/trivy
    state: link
    mode: '0755'

