---
- name: Provision DevOps Tools on Target Machines
  hosts: all
  become: true

  vars:
    jenkins_repo: https://pkg.jenkins.io/debian-stable
    nexus_version: "3.82.0-08"
    nexus_download_url: "https://download.sonatype.com/nexus/3/nexus-{{ nexus_version }}-linux-x86_64.tar.gz"
    nexus_install_dir: "/opt"
    nexus_user: "nexus"
    nexus_home: "/opt/nexus"
    nexus_data_dir: "/opt/sonatype-work"
    dependency_check_version: "8.4.0"
    sonar_version: "25.2.0.102705"
    sonar_user: "sonarqube"
    sonar_db_user: "sonaruser"
    sonar_db_pass: "Sonarpass"  # Replace securely in vault or var file
    sonar_db_name: "sonarqube"
    sonar_dir: "/opt/sonarqube"
    scanner_version: "7.0.1.4817"
    sonar_url: "http://127.0.0.1:9000"


  pre_tasks:
    - name: Update APT cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
      tags: update

  roles:
    - { role: java, tags: java }
    - { role: docker, tags: docker }
    - { role: jenkins, tags: jenkins }
    - { role: maven, tags: maven }
    - { role: nexus, tags: nexus }
    - { role: trivy, tags: trivy }
    - { role: owasp, tags: owasp }
    - { role: sonarqube, tags: sonarqube }
    - { role: prometheus, tags: prometheus }
    - { role: grafana, tags: grafana }