---
- name: Provision DevOps Tools on Target Machines
  hosts: all
  become: true

  vars:
    jenkins_repo: https://pkg.jenkins.io/debian-stable
    nexus_version: "3.82.0-08"
    nexus_bundle_name: "nexus-{{ nexus_version }}-linux-x86_64.tar.gz"
    nexus_download_url: "https://download.sonatype.com/nexus/3/{{ nexus_bundle_name }}"
    nexus_install_dir: "/opt/sonatype"
    nexus_extracted_dir: "{{ nexus_install_dir }}/nexus-{{ nexus_version }}"
    nexus_symlink_dir: "{{ nexus_install_dir }}/nexus"
    nexus_user: "nexus"
    nexus_group: "nexus"
    nexus_service_name: "nexus"
    nexus_log_file: "/opt/sonatype-work/nexus3/log/nexus.log"
    sonar_version: "25.2.0.102705"
    sonar_user: "sonarqube"
    sonar_db_user: "sonaruser"
    sonar_db_pass: "Sonarpass"  # Replace securely in vault or var file
    sonar_db_name: "sonarqube"
    sonar_dir: "/opt/sonarqube"
    scanner_version: "7.0.1.4817"
    sonar_url: "http://127.0.0.1:9000"
    prometheus_version: "2.45.0"
    prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dependency_check_version: "12.1.0"  # owap version
    trivy_version: "0.63.0"


  pre_tasks:
    - name: Update APT cache and upgrade packages
      apt:
        update_cache: yes
        upgrade: dist
      tags: update

  roles:
    - { role: java, tags: java }
    - { role: docker, tags: docker }
    - { role: jenkins, tags: jenkins }
    - { role: maven, tags: maven }
    - { role: nexus, tags: nexus }
    - { role: trivy, tags: trivy }
    - { role: owasp, tags: owasp }
    - { role: sonarqube, tags: sonarqube }
    - { role: prometheus, tags: prometheus }
    - { role: grafana, tags: grafana }
    - { role: helm, tags: helm }
