---
- name: Create prometheus user
  user:
    name: prometheus
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Download Prometheus archive
  get_url:
    url: "{{ prometheus_url }}"
    dest: "/tmp/prometheus.tar.gz"
    mode: '0644'

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes
    creates: "/opt/prometheus-{{ prometheus_version }}.linux-amd64"

- name: Symlink prometheus directory
  file:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64"
    dest: /opt/prometheus
    state: link
    force: yes

- name: Change ownership of Prometheus files
  file:
    path: /opt/prometheus*
    owner: prometheus
    group: prometheus
    recurse: yes

- name: Create Prometheus config directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Copy default Prometheus config
  copy:
    dest: /etc/prometheus/prometheus.yml
    content: |
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
    owner: prometheus
    group: prometheus
    mode: '0644'

- name: Create systemd service file for Prometheus
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/opt/prometheus/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Create Prometheus data directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
